#!/bin/sh
java \
	-Dorg.patrodyne.scripting.java.sourcepath="." \
	-Dorg.patrodyne.scripting.java.classpath="." \
	-jar target/patrodyne-scripting-javabang-*.jar $*
# vi:set tabstop=4 hardtabs=4 shiftwidth=4:
